POST https://node-first-api-hgt5.onrender.com/videos
Content-Type: application/json

{
    "title": "Video Teste do Render",
    "description": "Descrição video 02",
    "duration": 180
}

###

GET https://node-first-api-hgt5.onrender.com/videos

###

PUT  https://node-first-api-hgt5.onrender.com/videos/965a2c52-b1c7-4634-81a6-bc16e7c46170
Content-Type: application/json

{
    "title": "Video Iou",
    "description": "Descrição video 01 alterado",
    "duration": 180
}

###

DELETE   https://node-first-api-hgt5.onrender.com/videos/965a2c52-b1c7-4634-81a6-bc16e7c46170
Content-Type: application/json
